TARGET_BOARD_PLATFORM := android_ia

TARGET_ARCH := x86_64
TARGET_CPU_ABI := x86_64
TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := x86
TARGET_2ND_CPU_VARIANT := x86

BOARD_USE_64BIT_USERSPACE := true
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true

MALLOC_SVELTE := true

WITH_DEXPREOPT := true
WITH_DEXPREOPT_PIC := true

include device/asus/K013/board/*.mk
