TARGET_KERNEL_SOURCE := kernel/asus/me176c
TARGET_KERNEL_DEFCONFIG = $(BUILT_ME176C_DEFCONFIG)
TARGET_KERNEL_ARCH := x86_64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := x86_64-linux-android-
BOARD_KERNEL_IMAGE_NAME := bzImage

BOARD_KERNEL_CMDLINE += quiet androidboot.hardware=me176c rfkill.default_state=0

TARGET_USES_64_BIT_BINDER := true
ENABLE_CPUSETS := true
