BOARD_USES_FULL_RECOVERY_IMAGE := true
BOARD_CANT_BUILD_RECOVERY_FROM_BOOT_PATCH := true
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true

TW_THEME := portrait_hdpi
TWRP_INCLUDE_CRYPTO := true
TW_EXCLUDE_SUPERSU := true

TW_EXCLUDE_DEFAULT_USB_INIT := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/config/usb_gadget/g1/functions/mass_storage.0/lun.%d/file"
