WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER        := NL80211

WIFI_DRIVER_MODULE_NAME := brcmfmac
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/$(WIFI_DRIVER_MODULE_NAME).ko
