WIFI_DRIVER_STATE_CTRL_PARAM := /sys/class/rfkill/rfkill2/soft
WIFI_DRIVER_STATE_ON  := 0
WIFI_DRIVER_STATE_OFF := 1

WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_brcmfmac
BOARD_HOSTAPD_DRIVER := NL80211
